export const gameStates = {
  INACTIVE: 'INACTIVE',
  INITIALISING: 'INITIALISING',
  PENDING: 'PENDING',
  COUNTDOWN: 'COUNTDOWN',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};

export const gameConstants = {
  COUNTDOWN_LENGTH: 5,
};
